- name: Varibales in the play level
  hosts: all
  vars:
    msg: Rohith Kumar
  tasks:
    - name: To print variable
      ansible.builtin.debug:
        msg: "{{ msg }}"

    - name: Run time Variables
      ansible.builtin.debug:
        msg: "Bane extralu {{ beep }} ga"
        vars:
          beep: Mingutunavu ga


