- name: Error handling
  hosts: localhost
  tasks:
    - name: Valid shell module command
      ansible.builtin.shell: pwd

    - name: In valid shell module command
      ansible.builtin.shell: lss
      ignore_errors: yes

    - name: Valid shell module command
      ansible.builtin.shell: date