- name: Error handling
  hosts: localhost
  tasks:
    - name: Valid shell module command
      ansible.builtin.shell: pwd
      register: pwd

    - name: In valid shell module command
      ansible.builtin.shell: lss
      ignore_errors: yes

    - name: Valid shell module command
      ansible.builtin.shell: date
      register: date

    - name: Valid shell module command with filters in ansible
      ansible.builtin.debug:
        msg:
          - "{{ (date.stdout | split(','))[0] }}"
          - "{{ (pwd.stdout | split(','))[0] }}"

    - name: Anisble facts
      ansible.builtin.debug:
        msg: "{{ ansible_all_ipv4_addresses }}"
